# Generated by Django 4.2 on 2025-12-14 01:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la subcategoría', max_length=200, verbose_name='Nombre de la Subcategoría')),
                ('slug', models.SlugField(help_text='URL amigable generada automáticamente desde el nombre', max_length=250, unique=True, verbose_name='Slug (URL amigable)')),
                ('description', models.TextField(blank=True, help_text='Descripción breve de la subcategoría para los clientes', null=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono de Material-UI (ej: Smartphone, Computer)', max_length=100, null=True, verbose_name='Icono')),
                ('image', models.ImageField(blank=True, help_text='Imagen representativa de la subcategoría (JPG, PNG, GIF, WEBP)', null=True, upload_to='subcategories/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Imagen de la Subcategoría')),
                ('seo_title', models.CharField(blank=True, help_text='Título optimizado para motores de búsqueda (50-60 caracteres)', max_length=60, null=True, verbose_name='Título SEO')),
                ('seo_description', models.CharField(blank=True, help_text='Descripción meta para resultados de búsqueda (150-160 caracteres)', max_length=160, null=True, verbose_name='Descripción SEO')),
                ('seo_keywords', models.TextField(blank=True, help_text='Palabras clave separadas por comas para SEO', null=True, verbose_name='Palabras Clave (Keywords)')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la subcategoría está activa y visible en el catálogo', verbose_name='Activa')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización de la subcategoría dentro de su categoría', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha en que se eliminó la subcategoría (soft delete)', null=True, verbose_name='Fecha de Eliminación')),
                ('category', models.ForeignKey(help_text='Categoría a la que pertenece esta subcategoría', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='category.category', verbose_name='Categoría Padre')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
                'db_table': 'subcategories',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['slug'], name='subcategori_slug_af3bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['is_active'], name='subcategori_is_acti_fa690c_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category', 'order'], name='subcategori_categor_6a58ce_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['-created_at'], name='subcategori_created_d68ca0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'order')},
        ),
    ]
