# Generated by Django 4.2 on 2025-12-14 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la marca (ej: Nike, Apple, Samsung)', max_length=200, verbose_name='Nombre de la Marca')),
                ('slug', models.SlugField(help_text='URL amigable generada automáticamente desde el nombre', max_length=250, unique=True, verbose_name='Slug (URL amigable)')),
                ('description', models.TextField(blank=True, help_text='Descripción breve de la marca', null=True, verbose_name='Descripción')),
                ('logo', models.ImageField(blank=True, help_text='Logo de la marca (JPG, PNG, GIF, WEBP, SVG - preferible con fondo transparente)', null=True, upload_to='brands/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'])], verbose_name='Logo de la Marca')),
                ('website', models.URLField(blank=True, help_text='URL del sitio web oficial de la marca (ej: https://www.marca.com)', max_length=500, null=True, verbose_name='Sitio Web')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la marca está activa y visible en el catálogo', verbose_name='Activa')),
                ('is_featured', models.BooleanField(default=False, help_text='Marca destacada en la página principal', verbose_name='Destacada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha en que se eliminó la marca (soft delete)', null=True, verbose_name='Fecha de Eliminación')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'brands',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['slug'], name='brands_slug_6a4b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active'], name='brands_is_acti_101dba_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_featured'], name='brands_is_feat_0d5de1_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['-created_at'], name='brands_created_7310c4_idx'),
        ),
    ]
