# Generated by Django 4.2 on 2025-12-13 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la categoría', max_length=200, verbose_name='Nombre de la Categoría')),
                ('slug', models.SlugField(help_text='URL amigable generada automáticamente desde el nombre', max_length=250, unique=True, verbose_name='Slug (URL amigable)')),
                ('description', models.TextField(blank=True, help_text='Descripción breve de la categoría para los clientes', null=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono de Material-UI (ej: Smartphone, Computer)', max_length=100, null=True, verbose_name='Icono')),
                ('image', models.ImageField(blank=True, help_text='Imagen representativa de la categoría (JPG, PNG, GIF, WEBP)', null=True, upload_to='categories/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Imagen de la Categoría')),
                ('seo_title', models.CharField(blank=True, help_text='Título optimizado para motores de búsqueda (50-60 caracteres)', max_length=60, null=True, verbose_name='Título SEO')),
                ('seo_description', models.CharField(blank=True, help_text='Descripción meta para resultados de búsqueda (150-160 caracteres)', max_length=160, null=True, verbose_name='Descripción SEO')),
                ('seo_keywords', models.TextField(blank=True, help_text='Palabras clave separadas por comas para SEO', null=True, verbose_name='Palabras Clave (Keywords)')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la categoría está activa y visible en el catálogo', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha en que se eliminó la categoría (soft delete)', null=True, verbose_name='Fecha de Eliminación')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='categories_slug_b4303a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='categories_is_acti_aae090_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['-created_at'], name='categories_created_9211a1_idx'),
        ),
    ]
