# Generated by Django 4.2 on 2025-12-24 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('atributos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatorio', models.BooleanField(default=False, help_text='Indica si este atributo es obligatorio para productos de esta categoría', verbose_name='Obligatorio')),
                ('orden', models.IntegerField(default=0, help_text='Define el orden en que se muestra el atributo (menor número = mayor prioridad)', verbose_name='Orden de Visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('atributo', models.ForeignKey(help_text='Atributo asociado a la categoría', on_delete=django.db.models.deletion.CASCADE, related_name='categoria_atributos', to='atributos.attribute', verbose_name='Atributo')),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece este atributo', on_delete=django.db.models.deletion.CASCADE, related_name='categoria_atributos', to='category.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Categoría-Atributo',
                'verbose_name_plural': 'Categorías-Atributos',
                'db_table': 'categoria_atributos',
                'ordering': ['categoria', 'orden', 'atributo__name'],
            },
        ),
        migrations.AddIndex(
            model_name='categoriaatributo',
            index=models.Index(fields=['categoria', 'orden'], name='categoria_a_categor_af6bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriaatributo',
            index=models.Index(fields=['atributo'], name='categoria_a_atribut_4a2a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriaatributo',
            index=models.Index(fields=['obligatorio'], name='categoria_a_obligat_dae56b_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriaatributo',
            index=models.Index(fields=['-created_at'], name='categoria_a_created_e71159_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriaatributo',
            unique_together={('categoria', 'atributo')},
        ),
    ]
