# Generated by Django 4.2 on 2025-12-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del atributo (ej: Color, Talla, Capacidad, Material)', max_length=200, verbose_name='Nombre del Atributo')),
                ('slug', models.SlugField(help_text='URL amigable generada automáticamente desde el nombre', max_length=250, unique=True, verbose_name='Slug (URL amigable)')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del atributo', null=True, verbose_name='Descripción')),
                ('tipo_input', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('select', 'Selección'), ('color', 'Color'), ('checkbox', 'Checkbox'), ('radio', 'Radio')], default='text', help_text='Define cómo se mostrará el atributo en el formulario', max_length=20, verbose_name='Tipo de Input')),
                ('tipo_dato', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean')], default='string', help_text='Tipo de dato que almacenará el atributo', max_length=20, verbose_name='Tipo de Dato')),
                ('es_variable', models.BooleanField(default=True, help_text='Si afecta precio y/o stock de los productos', verbose_name='Es Variable')),
                ('es_filtrable', models.BooleanField(default=True, help_text='Si aparece en los filtros de búsqueda del catálogo', verbose_name='Es Filtrable')),
                ('orden', models.IntegerField(default=0, help_text='Menor número = mayor prioridad (0 por defecto)', verbose_name='Orden de Visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha en que se eliminó el atributo (soft delete)', null=True, verbose_name='Fecha de Eliminación')),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
                'db_table': 'attributes',
                'ordering': ['orden', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['slug'], name='attributes_slug_d6034d_idx'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['tipo_input'], name='attributes_tipo_in_77658c_idx'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['es_variable'], name='attributes_es_vari_517325_idx'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['es_filtrable'], name='attributes_es_filt_8ef98d_idx'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['orden'], name='attributes_orden_4530a3_idx'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['-created_at'], name='attributes_created_42cbce_idx'),
        ),
    ]
