# Generated by Django 4.2 on 2025-12-14 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atributos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(help_text='Valor del atributo (ej: Rojo, XL, 128GB, Algodón)', max_length=100, verbose_name='Valor')),
                ('valor_extra', models.CharField(blank=True, help_text='Información adicional del valor (ej: código hexadecimal #FF0000 para colores)', max_length=100, null=True, verbose_name='Valor Extra (Opcional)')),
                ('orden', models.IntegerField(default=0, help_text='Menor número aparece primero (0 por defecto)', verbose_name='Orden de Visualización')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el valor está activo y visible en formularios', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha en que se eliminó el valor (soft delete)', null=True, verbose_name='Fecha de Eliminación')),
                ('atributo', models.ForeignKey(help_text='Atributo al que pertenece este valor', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='atributos.attribute', verbose_name='Atributo')),
            ],
            options={
                'verbose_name': 'Valor de Atributo',
                'verbose_name_plural': 'Valores de Atributos',
                'db_table': 'attribute_values',
                'ordering': ['atributo', 'orden', 'valor'],
            },
        ),
        migrations.AddIndex(
            model_name='attributevalue',
            index=models.Index(fields=['atributo', 'orden'], name='attribute_v_atribut_749b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='attributevalue',
            index=models.Index(fields=['activo'], name='attribute_v_activo_cbe9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='attributevalue',
            index=models.Index(fields=['-created_at'], name='attribute_v_created_7d4e02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('atributo', 'orden')},
        ),
    ]
