# Generated by Django 4.2 on 2025-12-25 13:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, help_text='Nombre descriptivo del producto', max_length=255, verbose_name='Nombre del Producto')),
                ('slug', models.SlugField(help_text='URL amigable generada automáticamente desde el nombre', max_length=280, unique=True, verbose_name='Slug (URL amigable)')),
                ('sku_base', models.CharField(blank=True, help_text='Código único de identificación del producto', max_length=50, null=True, unique=True, verbose_name='SKU Base')),
                ('descripcion_corta', models.CharField(blank=True, help_text='Descripción breve del producto (máx. 300 caracteres)', max_length=300, verbose_name='Descripción Corta')),
                ('descripcion_larga', models.TextField(blank=True, help_text='Descripción detallada del producto con características completas', verbose_name='Descripción Larga')),
                ('tiene_variantes', models.BooleanField(default=False, help_text='Indica si el producto tiene variantes (tallas, colores, etc.)', verbose_name='Tiene Variantes')),
                ('tipo_producto', models.CharField(choices=[('simple', 'Simple'), ('variable', 'Variable'), ('digital', 'Digital')], default='simple', help_text='Tipo de producto: simple, variable o digital', max_length=10, verbose_name='Tipo de Producto')),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta del producto', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Base')),
                ('precio_costo', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de costo del producto', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Costo')),
                ('precio_descuento', models.DecimalField(blank=True, decimal_places=2, help_text='Precio con descuento aplicado', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio con Descuento')),
                ('porcentaje_descuento', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de descuento (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de Descuento')),
                ('moneda', models.CharField(default='COP', help_text='Código de moneda (ISO 4217)', max_length=3, verbose_name='Moneda')),
                ('stock_actual', models.IntegerField(default=0, help_text='Cantidad disponible en inventario', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Actual')),
                ('stock_minimo', models.IntegerField(default=0, help_text='Cantidad mínima de stock antes de reabastecer', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo')),
                ('unidad_medida', models.CharField(default='unidad', help_text='Unidad en la que se mide el producto', max_length=20, verbose_name='Unidad de Medida')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso del producto en gramos', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso (gramos)')),
                ('largo', models.DecimalField(blank=True, decimal_places=2, help_text='Largo del producto en centímetros', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Largo (cm)')),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, help_text='Ancho del producto en centímetros', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ancho (cm)')),
                ('alto', models.DecimalField(blank=True, decimal_places=2, help_text='Alto del producto en centímetros', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alto (cm)')),
                ('meta_title', models.CharField(blank=True, help_text='Título optimizado para motores de búsqueda (máx. 160 caracteres)', max_length=160, null=True, verbose_name='Título SEO')),
                ('meta_description', models.CharField(blank=True, help_text='Descripción meta para resultados de búsqueda (máx. 320 caracteres)', max_length=320, null=True, verbose_name='Descripción SEO')),
                ('keywords', models.CharField(blank=True, help_text='Palabras clave separadas por comas para SEO', max_length=500, null=True, verbose_name='Palabras Clave (Keywords)')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el producto está activo en el sistema', verbose_name='Activo')),
                ('publicado', models.BooleanField(default=False, help_text='Indica si el producto está publicado y visible en el catálogo', verbose_name='Publicado')),
                ('destacado', models.BooleanField(default=False, help_text='Indica si el producto aparece en la sección de destacados', verbose_name='Destacado')),
                ('es_nuevo', models.BooleanField(default=False, help_text='Indica si el producto se marca como nuevo', verbose_name='Es Nuevo')),
                ('fecha_publicacion', models.DateTimeField(blank=True, help_text='Fecha en que el producto fue publicado', null=True, verbose_name='Fecha de Publicación')),
                ('fecha_nuevo_hasta', models.DateTimeField(blank=True, help_text='Fecha hasta la cual el producto se considera nuevo', null=True, verbose_name="Fecha 'Nuevo' Hasta")),
                ('vistas', models.IntegerField(default=0, help_text='Número de veces que se ha visto el producto', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vistas')),
                ('ventas_totales', models.IntegerField(default=0, help_text='Número total de unidades vendidas', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ventas Totales')),
                ('rating_promedio', models.DecimalField(decimal_places=2, default=0.0, help_text='Calificación promedio del producto (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating Promedio')),
                ('total_reviews', models.IntegerField(default=0, help_text='Número total de reseñas del producto', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de Reviews')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha en que se eliminó el producto (soft delete)', null=True, verbose_name='Fecha de Eliminación')),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece el producto', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='category.category', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó el producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('marca', models.ForeignKey(blank=True, help_text='Marca del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='brands.brand', verbose_name='Marca')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuario que actualizó el producto por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='productos_nombre_d31432_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['slug'], name='productos_slug_2a7ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='productos_categor_169a62_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['marca'], name='productos_marca_i_c3b6be_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='productos_activo_aa3d01_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['publicado'], name='productos_publica_6e270d_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['destacado'], name='productos_destaca_126203_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['-created_at'], name='productos_created_1dedc5_idx'),
        ),
    ]
